### ISSUE TITLE
postdrop: warning: mail_queue_enter: create file maildrop/887233.343246: Permission denied

### ISSUE THREAD

**Issue by internethering** [systemd-cron/systemd-cron#75] opened 2021-07-28 10:21 UTC
```
Jul 28 12:14:29 alpha.test mail_on_failure[343246]: postdrop: warning: mail_queue_enter: create file maildrop/887233.343246: Permission denied
Jul 28 12:14:29 alpha.test postfix/postdrop[343246]: warning: mail_queue_enter: create file maildrop/887233.343246: Permission denied
```

`postfix check` shows no output, the mail system is operation without any problems. how to debug mail_on_failure?

postfix: 3.6.1
systemd-cron: 1.5.17

**Comment by smcv** [comment] 2021-09-15 12:28
I believe this is caused by the switch to `DynamicUser=yes`, which implies `NoNewPrivileges=yes`.

Postfix's `/usr/sbin/sendmail` relies on being able to run a setgid executable, `/usr/sbin/postdrop`, which has access to the `postdrop` group and therefore can write to `/var/spool/postfix/maildrop`. However, because systemd-cron's `mail_on_failure` is running with `PR_SET_NO_NEW_PRIVS`, it cannot gain privileges by running a setuid or setgid executable.

**Comment by a-detiste** [comment] 2021-09-26 21:42
So there's no clear solution

**Comment by smcv** [comment] 2021-09-26 22:43
I think the best solution might be to stop using `DynamicUser`, and instead use something like

```
[Service]
DynamicUser=no
User=_cron-failure
Group=systemd-journal
```

... and then install a `sysusers.d` snippet like `/usr/lib/sysusers.d/systemd-cron.conf` with something like

```
u _cron-failure -:systemd-journal - /nonexistent /usr/sbin/nologin
```

to create a non-dynamic `_cron-failure` system user to send the failure emails.

**Comment by mmokrejs** [comment] 2021-10-17 10:45
> I think the best solution might be to stop using `DynamicUser`, and instead use something like
> 
> ```
> [Service]
> DynamicUser=no
> User=_cron-failure
> Group=systemd-journal
> ```

I ran into this issue too when migrating from OpenRC to systemd on Gentoo Linux. About what file are you speaking here?

**Comment by internethering** [comment] 2021-12-16 11:40
I opened this bug 'n half of a year ago. May there someone from the devs, which can look after this?

**Comment by a-detiste** [comment] 2021-12-26 15:46
Fixed by release v1.5.18

**Closed by a-detiste** 2021-12-26 15:46 UTC
